### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by joliss** [fragsalat/lib-sass-data-uri#4]
There doesn't seem to be a license file in this repo. Do you want to add one, like an MIT license?

(I'm OK with my contribution in #3 to be licensed under whatever license you choose.)

**Comment by joliss** [comment]
Oh, I see that `package.json` says `"license": "ISC"`. Not sure if you want to add a copy of the ISC license or if that entry is enough. If the latter, feel free to just close this issue. :)

**Comment by fragsalat** [comment]
Actually I'm not deep in this license topic and don't know if there are any requirements to fulfill.

**Comment by joliss** [comment]
Guess it should be OK with the license tag in `package.json`. :)
